/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';
import type { Locale } from "@repo/i18n/types";
import type { introspection } from "./graphql-env.d";

declare module 'gql.tada' {
 interface setupCache {
    "\n  fragment ProviderProductDiscoveryProjection on ProductProjection {\n    id\n    name(locale: $locale)\n    description(locale: $locale)\n    slug(locale: $locale)\n    categories {\n      id\n      name(locale: $locale)\n      slug(locale: $locale)\n    }\n    productType {\n      key\n    }\n    masterVariant {\n      images {\n        url\n        label\n      }\n    }\n    allVariants {\n      id\n      sku\n      images {\n        url\n        label\n      }\n      attributesRaw {\n        name\n        value\n      }\n      price(\n        currency: $currency\n        channelId: $distributionChannelId\n        customerGroupId: $customerGroupId\n      ) {\n        value {\n          centAmount\n          currencyCode\n        }\n        discounted {\n          value {\n            centAmount\n            currencyCode\n          }\n        }\n      }\n      availability {\n        channels(includeChannelIds: $supplyChannelIds) {\n          results {\n            availability {\n              availableQuantity\n            }\n          }\n        }\n      }\n    }\n  }\n":
      TadaDocumentNode<{ id: string; name: string | null; description: string | null; slug: string | null; categories: { id: string; name: string | null; slug: string | null; }[]; productType: { key: string | null; } | null; masterVariant: { images: { url: string; label: string | null; }[]; }; allVariants: { id: number; sku: string | null; images: { url: string; label: string | null; }[]; attributesRaw: { name: string; value: JSON; }[]; price: { value: { __typename?: "HighPrecisionMoney" | undefined; centAmount: number; currencyCode: string; } | { __typename?: "Money" | undefined; centAmount: number; currencyCode: string; }; discounted: { value: { __typename?: "HighPrecisionMoney" | undefined; centAmount: number; currencyCode: string; } | { __typename?: "Money" | undefined; centAmount: number; currencyCode: string; }; } | null; } | null; availability: { channels: { results: { availability: { availableQuantity: number | null; }; }[]; }; } | null; }[]; }, {}, { fragment: "ProviderProductDiscoveryProjection"; on: "ProductProjection"; masked: true; }>;
    "\n    query ProviderProductBySlug(\n      $filters: [SearchFilterInput!]\n      $locale: Locale!\n      $currency: Currency!\n      $distributionChannelId: String!\n      $supplyChannelIds: [String!]\n      $customerGroupId: String\n    ) {\n      productProjectionSearch(filters: $filters, limit: 1) {\n        results {\n          ...ProviderProductDiscoveryProjection\n        }\n      }\n    }\n  ":
      TadaDocumentNode<{ productProjectionSearch: { results: { [$tada.fragmentRefs]: { ProviderProductDiscoveryProjection: "ProductProjection"; }; }[]; }; }, { customerGroupId?: string | null | undefined; supplyChannelIds?: string[] | null | undefined; distributionChannelId: string; currency: string; locale: "en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL"; filters?: { string?: string | null | undefined; model?: { tree?: { subTreeValues: string[]; rootValues: string[]; path: string; } | null | undefined; exists?: { path: string; } | null | undefined; missing?: { path: string; } | null | undefined; range?: { ranges: { to: string; from: string; }[]; path: string; } | null | undefined; value?: { values: string[]; path: string; } | null | undefined; } | null | undefined; }[] | null | undefined; }, void>;
    "\n  query ResolveProviderProductStore($storeKey: String!) {\n    store(key: $storeKey) {\n      distributionChannels {\n        id\n      }\n      supplyChannels {\n        id\n      }\n    }\n  }\n":
      TadaDocumentNode<{ store: { distributionChannels: { id: string; }[]; supplyChannels: { id: string; }[]; } | null; }, { storeKey: string; }, void>;
    "\n  query ResolveProviderProductCustomerGroup($customerId: String!) {\n    customer(id: $customerId) {\n      customerGroup {\n        id\n      }\n    }\n  }\n":
      TadaDocumentNode<{ customer: { customerGroup: { id: string; } | null; } | null; }, { customerId: string; }, void>;
    "\n  query ProviderProductSelectionAssignments(\n    $storeKey: KeyReferenceInput!\n    $where: String!\n    $limit: Int!\n    $offset: Int!\n  ) {\n    inStore(key: $storeKey) {\n      productSelectionAssignments(\n        where: $where\n        limit: $limit\n        offset: $offset\n      ) {\n        total\n        results {\n          productSelection {\n            mode\n          }\n          productRef {\n            id\n          }\n          variantSelection {\n            type\n            skus\n          }\n          variantExclusion {\n            skus\n          }\n        }\n      }\n    }\n  }\n":
      TadaDocumentNode<{ inStore: { productSelectionAssignments: { total: number; results: { productSelection: { mode: "Individual" | "IndividualExclusion"; } | null; productRef: { id: string; }; variantSelection: { __typename?: "ProductVariantSelectionIncludeAllExcept" | undefined; type: string; skus: string[]; } | { __typename?: "ProductVariantSelectionIncludeOnly" | undefined; type: string; skus: string[]; } | null; variantExclusion: { skus: string[]; } | null; }[]; }; }; }, { offset: number; limit: number; where: string; storeKey: unknown; }, void>;
  }
}
