projects:
  cms-drupal:
    schema: './packages/cms-drupal/gql/schema.graphql'
    documents: ['./packages/cms-drupal/**/*.{graphql,js,ts,jsx,tsx}']
  commerce-commercetools:
    schema: './packages/commerce-commercetools/gql/schema.graphql'
    documents: ['./packages/commerce-commercetools/**/*.{graphql,js,ts,jsx,tsx}']
