projects:
  cms-contentstack:
    schema: "./packages/cms-contentstack/gql/schema.graphql"
    documents:
      - "./packages/cms-contentstack/*.{ts,tsx}"
      - "./packages/cms-contentstack/!(node_modules|gql)/**/*.{ts,tsx}"
  cms-drupal:
    schema: "./packages/cms-drupal/gql/schema.graphql"
    documents:
      - "./packages/cms-drupal/*.{ts,tsx}"
      - "./packages/cms-drupal/!(node_modules|gql)/**/*.{ts,tsx}"
  commerce-commercetools:
    schema: "./packages/commerce-commercetools/gql/schema.graphql"
    documents:
      - "./packages/commerce-commercetools/*.{ts,tsx}"
      - "./packages/commerce-commercetools/!(node_modules|gql)/**/*.{ts,tsx}"
