projects:
  cms:
    schema: './packages/cms-contentstack/gql/schema.graphql'
    documents: ['./packages/cms-contentstack/**/*.{graphql,js,ts,jsx,tsx}']
  commerce:
    schema: './packages/commerce/gql/schema.graphql'
    documents: ['./packages/commerce/**/*.{graphql,js,ts,jsx,tsx}']
  commerce-commercetools:
    schema: './packages/commerce-commercetools/gql/schema.graphql'
    documents: ['./packages/commerce-commercetools/**/*.{graphql,js,ts,jsx,tsx}']
