/**
 * Algolia's native commercetools connector requires every commercetools View
 * permission, View API clients, and Subscriptions. The connector credential
 * intentionally excludes project and API-client management.
 */
export const ALGOLIA_COMMERCETOOLS_CONNECTOR_SCOPE_NAMES = [
  "view_api_clients",
  "view_project_settings",
  "view_stores",
  "view_tax_categories",
  "view_products",
  "view_product_types",
  "view_channels",
  "view_product_discounts",
  "view_published_products",
  "view_attribute_groups",
  "view_product_selections",
  "view_categories",
  "view_standalone_prices",
  "view_cart_discounts",
  "view_discount_codes",
  "view_customers",
  "view_customer_groups",
  "view_business_units",
  "view_associate_roles",
  "view_approval_rules",
  "view_approval_flows",
  "view_orders",
  "view_recurring_orders",
  "view_recurrence_policies",
  "view_payment_methods",
  "view_payments",
  "view_shopping_lists",
  "view_order_edits",
  "view_shipping_methods",
  "view_zones",
  "view_quote_requests",
  "view_staged_quotes",
  "view_quotes",
  "view_types",
  "view_key_value_documents",
  "view_messages",
  "view_states",
  "view_audit_log",
  "manage_subscriptions",
] as const;
