/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';
import type { Locale } from "@repo/i18n/types";

declare module 'gql.tada' {
 interface setupCache {
    "\n  fragment Channel on Channel {\n    id\n    key\n    version\n    name(locale: $locale)\n  }\n":
      TadaDocumentNode<{ id: string; key: string; version: number; name: string | null; }, {}, { fragment: "Channel"; on: "Channel"; masked: true; }>;
    "\n  fragment Store on Store {\n    id\n    key\n    version\n    name(locale: $locale)\n    languages\n    countries {\n      code\n    }\n    distributionChannels {\n      ...Channel\n    }\n    supplyChannels {\n      ...Channel\n    }\n  }\n":
      TadaDocumentNode<{ id: string; key: string; version: number; name: string | null; languages: ("en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL")[] | null; countries: { code: string; }[] | null; distributionChannels: { [$tada.fragmentRefs]: { Channel: "Channel"; }; }[]; supplyChannels: { [$tada.fragmentRefs]: { Channel: "Channel"; }; }[]; }, {}, { fragment: "Store"; on: "Store"; masked: true; }>;
    "\n    query getStoreByKey($key: String!, $locale: Locale!) {\n      store(key: $key) {\n        ...Store\n      }\n    }\n  ":
      TadaDocumentNode<{ store: { [$tada.fragmentRefs]: { Store: "Store"; }; } | null; }, { locale: "en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL"; key: string; }, void>;
    "\n        query getProductSelectionAssignments($storeKey: KeyReferenceInput!, $where: String!, $limit: Int) {\n          inStore(key: $storeKey) {\n            productSelectionAssignments(where: $where, limit: $limit) {\n              results {\n                productSelection {\n                  mode\n                }\n                productRef {\n                  id\n                }\n                variantSelection {\n                  type\n                  skus\n                }\n                variantExclusion {\n                  skus\n                }\n              }\n            }\n          }\n        }\n      ":
      TadaDocumentNode<{ inStore: { productSelectionAssignments: { results: { productSelection: { mode: "Individual" | "IndividualExclusion"; } | null; productRef: { id: string; }; variantSelection: { __typename?: "ProductVariantSelectionIncludeAllExcept" | undefined; type: string; skus: string[]; } | { __typename?: "ProductVariantSelectionIncludeOnly" | undefined; type: string; skus: string[]; } | null; variantExclusion: { skus: string[]; } | null; }[]; }; }; }, { limit?: number | null | undefined; where: string; storeKey: unknown; }, void>;
    "\n  fragment ProductPriceSearch on ProductPriceSearch {\n    value {\n      centAmount\n      currencyCode\n    }\n    discounted {\n      value {\n        centAmount\n        currencyCode\n      }\n    }\n  }\n":
      TadaDocumentNode<{ value: { __typename?: "HighPrecisionMoney" | undefined; centAmount: number; currencyCode: string; } | { __typename?: "Money" | undefined; centAmount: number; currencyCode: string; }; discounted: { value: { __typename?: "HighPrecisionMoney" | undefined; centAmount: number; currencyCode: string; } | { __typename?: "Money" | undefined; centAmount: number; currencyCode: string; }; } | null; }, {}, { fragment: "ProductPriceSearch"; on: "ProductPriceSearch"; masked: true; }>;
    "\n  fragment ProductPrice on ProductPrice {\n    value {\n      centAmount\n      currencyCode\n    }\n    discounted {\n      value {\n        centAmount\n        currencyCode\n      }\n    }\n  }\n":
      TadaDocumentNode<{ value: { __typename?: "HighPrecisionMoney" | undefined; centAmount: number; currencyCode: string; } | { __typename?: "Money" | undefined; centAmount: number; currencyCode: string; }; discounted: { value: { __typename?: "HighPrecisionMoney" | undefined; centAmount: number; currencyCode: string; } | { __typename?: "Money" | undefined; centAmount: number; currencyCode: string; }; } | null; }, {}, { fragment: "ProductPrice"; on: "ProductPrice"; masked: true; }>;
    "\n  fragment CartFields on Cart {\n    id\n    version\n    country\n    store {\n      key\n    }\n    lineItems {\n      id\n      key\n      productId\n      productType {\n        key\n      }\n      name(locale: $locale)\n      quantity\n      variant {\n        id\n        sku\n        attributesRaw {\n          name\n          value\n        }\n        images {\n          url\n          label\n        }\n      }\n      price {\n          ... ProductPrice\n      }\n      totalPrice {\n        currencyCode\n        centAmount\n      }\n    }\n    totalLineItemQuantity\n    totalPrice {\n      currencyCode\n      centAmount\n    }\n    version\n    cartState\n  }\n":
      TadaDocumentNode<{ id: string; version: number; country: string | null; store: { key: string; } | null; lineItems: { id: string; key: string | null; productId: string; productType: { key: string | null; } | null; name: string | null; quantity: number; variant: { id: number; sku: string | null; attributesRaw: { name: string; value: JSON; }[]; images: { url: string; label: string | null; }[]; } | null; price: { [$tada.fragmentRefs]: { ProductPrice: "ProductPrice"; }; }; totalPrice: { currencyCode: string; centAmount: number; } | null; }[]; totalLineItemQuantity: number | null; totalPrice: { currencyCode: string; centAmount: number; }; cartState: "Active" | "Frozen" | "Merged" | "Ordered"; }, {}, { fragment: "CartFields"; on: "Cart"; masked: true; }>;
    "\n  mutation CreateCart($currency: Currency!, $storeId: String!, $locale: Locale!) {\n    createCart(\n      draft: {\n        currency: $currency\n        store: {\n          id: $storeId\n        }\n      }\n    ) {\n      ...CartFields\n    }\n  }\n":
      TadaDocumentNode<{ createCart: { [$tada.fragmentRefs]: { CartFields: "Cart"; }; } | null; }, { locale: "en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL"; storeId: string; currency: string; }, void>;
    "\n  query GetActiveCart($customerId: String!, $locale: Locale!) {\n    customerActiveCart(customerId: $customerId) {\n      ...CartFields\n    }\n  }\n":
      TadaDocumentNode<{ customerActiveCart: { [$tada.fragmentRefs]: { CartFields: "Cart"; }; } | null; }, { locale: "en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL"; customerId: string; }, void>;
    "\n  query CartById($id: String!, $locale: Locale!) {\n    cart(id: $id) {\n      ...CartFields\n    }\n  }\n":
      TadaDocumentNode<{ cart: { [$tada.fragmentRefs]: { CartFields: "Cart"; }; } | null; }, { locale: "en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL"; id: string; }, void>;
    "\n  mutation AddItemToCart($id: String!, $version: Long!, $productId: String!, $variantId: Int!, $quantity: Long!, $distributionChannelKey: String!, $locale: Locale!) {\n    updateCart(\n      id: $id\n      version: $version\n      actions: [\n        {\n          addLineItem: {\n            productId: $productId\n            variantId: $variantId\n            quantity: $quantity\n            distributionChannel: { key: $distributionChannelKey }\n          }\n        }\n      ]\n    ) {\n      ...CartFields\n    }\n  }\n":
      TadaDocumentNode<{ updateCart: { [$tada.fragmentRefs]: { CartFields: "Cart"; }; } | null; }, { locale: "en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL"; distributionChannelKey: string; quantity: number; variantId: number; productId: string; version: number; id: string; }, void>;
    "\n    mutation ChangeItemQuantity($id: String!, $version: Long!, $lineItemId: String!, $quantity: Long!, $locale: Locale!) {\n      updateCart(\n        id: $id\n        version: $version\n        actions: [\n          {\n            changeLineItemQuantity: {\n              lineItemId: $lineItemId\n              quantity: $quantity\n            }\n          }\n        ]\n      ) {\n        ...CartFields\n      }\n    }\n  ":
      TadaDocumentNode<{ updateCart: { [$tada.fragmentRefs]: { CartFields: "Cart"; }; } | null; }, { locale: "en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL"; quantity: number; lineItemId: string; version: number; id: string; }, void>;
    "\n  mutation RemoveItemFromCart($id: String!, $version: Long!, $lineItemId: String!, $locale: Locale!) {\n    updateCart(\n      id: $id\n      version: $version\n      actions: [\n        {\n          removeLineItem: {\n            lineItemId: $lineItemId\n          }\n        }\n      ]\n    ) {\n      ...CartFields\n    }\n  }":
      TadaDocumentNode<{ updateCart: { [$tada.fragmentRefs]: { CartFields: "Cart"; }; } | null; }, { locale: "en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL"; lineItemId: string; version: number; id: string; }, void>;
    "\n  fragment ProductSearchVariantAvailability on ProductSearchVariantAvailability {\n    id\n    version\n    isOnStock\n    restockableInDays\n    availableQuantity\n  }\n":
      TadaDocumentNode<{ id: string | null; version: number | null; isOnStock: boolean; restockableInDays: number | null; availableQuantity: number | null; }, {}, { fragment: "ProductSearchVariantAvailability"; on: "ProductSearchVariantAvailability"; masked: true; }>;
    "\n  fragment ProductSearchVariantAvailabilityWithChannels on ProductSearchVariantAvailabilityWithChannels {\n    noChannel {\n      ...ProductSearchVariantAvailability\n    }\n    channels(includeChannelIds: $supplyChannelIds) {\n      results {\n        channel {\n          ...Channel\n        }\n        availability {\n          ...ProductSearchVariantAvailability\n        }\n      }\n    }\n  }\n":
      TadaDocumentNode<{ noChannel: { [$tada.fragmentRefs]: { ProductSearchVariantAvailability: "ProductSearchVariantAvailability"; }; } | null; channels: { results: { channel: { [$tada.fragmentRefs]: { Channel: "Channel"; }; } | null; availability: { [$tada.fragmentRefs]: { ProductSearchVariantAvailability: "ProductSearchVariantAvailability"; }; }; }[]; }; }, {}, { fragment: "ProductSearchVariantAvailabilityWithChannels"; on: "ProductSearchVariantAvailabilityWithChannels"; masked: true; }>;
    "\n  fragment ProductSearchVariant on ProductSearchVariant {\n    id\n    sku\n    images {\n      url\n      label\n    }\n    attributesRaw {\n      name\n      value\n    }\n    price(currency: $currency, channelId: $distributionChannelId) {\n      ...ProductPriceSearch\n    }\n    availability {\n      ...ProductSearchVariantAvailabilityWithChannels\n    }\n  }\n":
      TadaDocumentNode<{ id: number; sku: string | null; images: { url: string; label: string | null; }[]; attributesRaw: { name: string; value: JSON; }[]; price: { [$tada.fragmentRefs]: { ProductPriceSearch: "ProductPriceSearch"; }; } | null; availability: { [$tada.fragmentRefs]: { ProductSearchVariantAvailabilityWithChannels: "ProductSearchVariantAvailabilityWithChannels"; }; } | null; }, {}, { fragment: "ProductSearchVariant"; on: "ProductSearchVariant"; masked: true; }>;
    "\n  fragment ProductCard on ProductProjection {\n    id\n    key\n    productType {\n      key\n    }\n    name(locale: $locale)\n    description(locale: $locale)\n    slug(locale: $locale)\n    masterVariant {\n      images {\n        url\n        label\n      }\n    }\n    allVariants {\n      ...ProductSearchVariant\n    }\n  }\n":
      TadaDocumentNode<{ id: string; key: string | null; productType: { key: string | null; } | null; name: string | null; description: string | null; slug: string | null; masterVariant: { images: { url: string; label: string | null; }[]; }; allVariants: { [$tada.fragmentRefs]: { ProductSearchVariant: "ProductSearchVariant"; }; }[]; }, {}, { fragment: "ProductCard"; on: "ProductProjection"; masked: true; }>;
    "\n  fragment ProductPage on ProductProjection {\n    id\n    key\n    version\n    lastModifiedAt\n    name(locale: $locale)\n    description(locale: $locale)\n    slug(locale: $locale)\n    categories {\n      id\n      key\n      name(locale: $locale)\n      slug(locale: $locale)\n    }\n    productType {\n      key\n    }\n    masterVariant {\n      sku\n      images {\n        url\n        label\n      }\n      ...ProductSearchVariant\n    }\n    allVariants {\n      sku\n      images {\n        url\n        label\n      }\n      ...ProductSearchVariant\n    }\n  }\n":
      TadaDocumentNode<{ id: string; key: string | null; version: number; lastModifiedAt: string; name: string | null; description: string | null; slug: string | null; categories: { id: string; key: string | null; name: string | null; slug: string | null; }[]; productType: { key: string | null; } | null; masterVariant: { sku: string | null; images: { url: string; label: string | null; }[]; [$tada.fragmentRefs]: { ProductSearchVariant: "ProductSearchVariant"; }; }; allVariants: { sku: string | null; images: { url: string; label: string | null; }[]; [$tada.fragmentRefs]: { ProductSearchVariant: "ProductSearchVariant"; }; }[]; }, {}, { fragment: "ProductPage"; on: "ProductProjection"; masked: true; }>;
    "\n    query GetProductBySlug(\n      $filters: [SearchFilterInput!]\n      $locale: Locale!\n      $currency: Currency!\n      $distributionChannelId: String!\n      $supplyChannelIds: [String!]\n    ) {\n      productProjectionSearch(filters: $filters, limit: 1) {\n        results {\n          id\n          ...ProductPage\n        }\n      }\n    }\n  ":
      TadaDocumentNode<{ productProjectionSearch: { results: { id: string; [$tada.fragmentRefs]: { ProductPage: "ProductProjection"; }; }[]; }; }, { supplyChannelIds?: string[] | null | undefined; distributionChannelId: string; currency: string; locale: "en-US" | "en-GB" | "es-ES" | "fr-FR" | "de-DE" | "it-IT" | "pt-PT" | "nl-NL"; filters?: { string?: string | null | undefined; model?: { tree?: { subTreeValues: string[]; rootValues: string[]; path: string; } | null | undefined; exists?: { path: string; } | null | undefined; missing?: { path: string; } | null | undefined; range?: { ranges: { to: string; from: string; }[]; path: string; } | null | undefined; value?: { values: string[]; path: string; } | null | undefined; } | null | undefined; }[] | null | undefined; }, void>;
  }
}
