/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';

declare module 'gql.tada' {
 interface setupCache {
    "\n    fragment ProductCards on ProductCards {\n      title\n      category\n    }\n":
      TadaDocumentNode<{ title: string | null; category: unknown; }, {}, { fragment: "ProductCards"; on: "ProductCards"; masked: true; }>;
    "\n    fragment Tabs on Tabs {\n      heading\n      tabs_blocks {\n        __typename\n        ... on TabsTabsBlocksTab {\n          tab {\n            label\n            content {\n              __typename\n              ... on TabsTabsBlocksTabBlockContentRichText {\n                rich_text {\n                  content {\n                    json\n                  }\n                }\n              }\n              ... on TabsTabsBlocksTabBlockContentCardCollection {\n                card_collection {\n                  contentConnection {\n                    __typename\n                    edges {\n                      node {\n                        __typename\n                        ... on TabsTabsBlocksTabBlockContentCardCollectionBlockContentNode {\n                          __typename\n                          ... on Product {\n                            title\n                          }\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      styling {\n        background_pattern\n        background_and_field_pattern_color\n      }\n    }\n":
      TadaDocumentNode<{ heading: string | null; tabs_blocks: unknown; styling: { background_pattern: string | null; background_and_field_pattern_color: string | null; } | null; }, {}, { fragment: "Tabs"; on: "Tabs"; masked: true; }>;
    "\n      query PageQuery($url: String, $locale: String) {\n        all_page(locale: $locale, fallback_locale: true, limit: 1, where:  {\n           url: $url\n        }) {\n        items {\n          title\n          url\n          headline\n          components {\n            __typename\n            ... on PageComponentsProductCards {\n              product_cards {\n                __typename\n                ...ProductCards\n              }\n            }\n            ... on PageComponentsTabs {\n              tabs {\n                __typename\n                ...Tabs\n              }\n            }\n          }\n          system {\n            uid\n            content_type_uid\n            locale\n          }\n        }\n      }\n      }\n    ":
      TadaDocumentNode<{ all_page: { items: ({ title: string | null; url: string | null; headline: string | null; components: ({ __typename: "PageComponentsProductCards"; product_cards: { __typename: "ProductCards"; [$tada.fragmentRefs]: { ProductCards: "ProductCards"; }; } | null; } | { __typename: "PageComponentsTabs"; tabs: { __typename: "Tabs"; [$tada.fragmentRefs]: { Tabs: "Tabs"; }; } | null; } | { __typename: "PageComponentsTextBlock"; } | null)[] | null; system: { uid: string | null; content_type_uid: string | null; locale: string | null; } | null; } | null)[] | null; } | null; }, { locale?: string | null | undefined; url?: string | null | undefined; }, void>;
    "\n  query getMenu($locale: String!) {\n    all_navigation(locale: $locale, fallback_locale: true) {\n      items {\n        system {\n          uid\n          content_type_uid\n        }\n        title\n        items {\n          text\n          linkConnection {\n            edges {\n              node {\n                ... on Page {\n                  system {\n                    uid\n                    content_type_uid\n                  }\n                  url\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n":
      TadaDocumentNode<{ all_navigation: { items: ({ system: { uid: string | null; content_type_uid: string | null; } | null; title: string | null; items: ({ text: string | null; linkConnection: { edges: ({ node: { __typename?: "Page" | undefined; system: { uid: string | null; content_type_uid: string | null; } | null; url: string | null; } | null; } | null)[] | null; } | null; } | null)[] | null; } | null)[] | null; } | null; }, { locale: string; }, void>;
  }
}
