/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';

declare module 'gql.tada' {
 interface setupCache {
    "\n    fragment HeroSection on HeroSection {\n      tagline\n      title\n      description {\n        json\n      }\n      imageConnection {\n        edges {\n          node {\n            ... on SysAsset {\n              url\n              dimension {\n                width\n                height\n              }\n            }\n          }\n        }\n      }\n      image_alt\n      cta {\n        label\n        internal_contentConnection {\n          edges {\n            node {\n              ... on LandingPage {\n                url\n                title\n              }\n            }\n          }\n        }\n        external_url\n      }\n    }\n":
      TadaDocumentNode<{ tagline: string | null; title: string | null; description: { json: unknown; } | null; imageConnection: { edges: ({ node: { url: string | null; dimension: { width: number | null; height: number | null; } | null; } | null; } | null)[] | null; } | null; image_alt: string | null; cta: ({ label: string | null; internal_contentConnection: { edges: ({ node: { __typename?: "LandingPage" | undefined; url: string | null; title: string | null; } | null; } | null)[] | null; } | null; external_url: string | null; } | null)[] | null; }, {}, { fragment: "HeroSection"; on: "HeroSection"; masked: true; }>;
    "\n        query PageQuery($url: String, $locale: String!) {\n            all_landing_page(\n                locale: $locale\n                fallback_locale: true\n                limit: 1\n                where: { url: $url }\n            ) {\n                items {\n                    title\n                    url\n                    components {\n                        __typename\n                        ... on LandingPageComponentsHeroSection {\n                            hero_section {\n                                __typename\n                                ...HeroSection\n                            }\n                        }\n                    }\n                    system {\n                        uid\n                        content_type_uid\n                        locale\n                    }\n                }\n            }\n        }\n    ":
      TadaDocumentNode<{ all_landing_page: { items: ({ title: string | null; url: string | null; components: ({ __typename: "LandingPageComponentsHeroSection"; hero_section: { __typename: "HeroSection"; [$tada.fragmentRefs]: { HeroSection: "HeroSection"; }; } | null; } | null)[] | null; system: { uid: string | null; content_type_uid: string | null; locale: string | null; } | null; } | null)[] | null; } | null; }, { locale: string; url?: string | null | undefined; }, void>;
    "\n  query getMenu($locale: String!) {\n    all_navigation(locale: $locale, fallback_locale: true) {\n      items {\n        system {\n          uid\n          content_type_uid\n        }\n        title\n        items {\n          text\n          linkConnection {\n            edges {\n              node {\n                ... on LandingPage {\n                  system {\n                    uid\n                    content_type_uid\n                  }\n                  url\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n":
      TadaDocumentNode<{ all_navigation: { items: ({ system: { uid: string | null; content_type_uid: string | null; } | null; title: string | null; items: ({ text: string | null; linkConnection: { edges: ({ node: { __typename?: "LandingPage" | undefined; system: { uid: string | null; content_type_uid: string | null; } | null; url: string | null; } | null; } | null)[] | null; } | null; } | null)[] | null; } | null)[] | null; } | null; }, { locale: string; }, void>;
  }
}
