import { NodeTerminal } from "@effect/platform-node";
import { expect, it } from "@effect/vitest";
import {
  Deferred,
  Effect,
  Fiber,
  FileSystem,
  Layer,
  PlatformError,
  Ref,
  Schema,
  Stdio,
} from "effect";
import { TestConsole } from "effect/testing";
import { Command } from "effect/unstable/cli";
import { ChildProcessSpawner } from "effect/unstable/process";
import { afterEach, beforeEach, describe, vi } from "vitest";

import { command } from "../src/commands.ts";
import { Workspaces } from "../src/workspaces.ts";
import {
  memoryWorkspace,
  memoryWorkspaceServices,
} from "./fixtures/memory-workspace.ts";
import {
  installedApplication,
  packageManager,
} from "./fixtures/package-manager.ts";

describe("dependency synchronization", () => {
  const root = "/source/workspaces/configured-site";
  // Keep real user/npm-run configuration out of controlled process tests.
  beforeEach(() => {
    for (const name of Object.keys(process.env)) {
      if (
        name.toLowerCase().startsWith("npm_config_") ||
        name.startsWith("PNPM_")
      ) {
        vi.stubEnv(name, undefined);
      }
    }
  });
  afterEach(() => vi.unstubAllEnvs());
  const named = Workspaces.pipe(
    Effect.flatMap((api) =>
      api.named({ name: "configured-site", sourceRoot: "/source" })
    )
  );
  const installed = installedApplication(root);
  const processes = Layer.effect(
    ChildProcessSpawner.ChildProcessSpawner,
    packageManager(() => installed)
  );

  it.effect(
    "keeps installed dependencies current across credential rotation but reconciles registry configuration",
    () =>
      Effect.gen(function* () {
        const layer = yield* memoryWorkspace("application", { processes });
        yield* Effect.gen(function* () {
          const fs = yield* FileSystem.FileSystem;
          const configuration = "/source/.npmrc";
          yield* fs.writeFileString(
            configuration,
            "# Registry login\n//registry.npmjs.org/:_authToken=first-test-token\n"
          );
          yield* (yield* named).sync({});
          const receipt = yield* fs.readFileString(
            `${root}/.workspace-composition.json`
          );
          expect(receipt).not.toContain("first-test-token");
          yield* fs.writeFileString(
            configuration,
            "//registry.npmjs.org/:_authToken=rotated-test-token\n"
          );
          expect(yield* (yield* named).check()).toMatchObject({
            dependencies: "current",
            ready: true,
          });
          expect(
            yield* fs.readFileString(`${root}/.workspace-composition.json`)
          ).toBe(receipt);

          yield* fs.writeFileString(
            configuration,
            "//registry.npmjs.org/:_authToken=rotated-test-token\nregistry=https://registry.example.test\n"
          );
          expect(yield* (yield* named).check()).toMatchObject({
            dependencies: "pending",
            ready: false,
          });
          const failedInstaller = Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() => Effect.succeed(9))
          );
          expect(
            yield* named.pipe(
              Effect.flatMap((workspace) => workspace.sync({})),
              Effect.provide(memoryWorkspaceServices([], failedInstaller)),
              Effect.flip
            )
          ).toMatchObject({
            _tag: "DependencyInstallationFailed",
            phase: "exit",
          });
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect(
    "keeps CLI Check current with unrelated local files but rejects missing dependencies",
    () =>
      Effect.gen(function* () {
        const layer = yield* memoryWorkspace("application", { processes });
        yield* Effect.gen(function* () {
          const fs = yield* FileSystem.FileSystem;
          yield* (yield* named).sync({});
          yield* fs.writeFileString(`${root}/notes.md`, "Local scratch notes");
          yield* fs.makeDirectory(`${root}/apps/web/local-build`, {
            recursive: true,
          });
          yield* fs.writeFileString(
            `${root}/apps/web/local-build/output.data`,
            "Generated by a local tool"
          );
          const check = Command.runWith(command("/source"), {
            version: "0.3.0",
          })(["compose", "configured-site", "--check"]).pipe(
            Effect.provide([
              memoryWorkspaceServices(),
              NodeTerminal.layer,
              Stdio.layerTest({}),
            ]),
            Effect.provideService(
              ChildProcessSpawner.ChildProcessSpawner,
              ChildProcessSpawner.make(() =>
                Effect.die(new Error("Unexpected process during Check"))
              )
            )
          );
          yield* check;
          expect((yield* TestConsole.logLines).join("\n")).toContain(
            "configured-site: current."
          );
          const manifest = `${root}/apps/web/node_modules/next/package.json`;
          yield* fs.remove(manifest);
          yield* fs.makeDirectory(manifest);
          expect(yield* check.pipe(Effect.flip)).toMatchObject({
            _tag: "WorkspaceNotCurrent",
          });
          expect((yield* fs.stat(manifest)).type).toBe("Directory");
        }).pipe(Effect.provide([layer, TestConsole.layer]));
      })
  );

  it.effect(
    "recognizes pnpm normalization but requires installation for a new dependency declaration",
    () =>
      Effect.gen(function* () {
        const layer = yield* memoryWorkspace("application", {
          processes: Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() =>
              Effect.gen(function* () {
                const fs = yield* FileSystem.FileSystem;
                const lock = yield* fs.readFileString(`${root}/pnpm-lock.yaml`);
                yield* fs.writeFileString(
                  `${root}/pnpm-lock.yaml`,
                  `${lock}\n# normalized by installer\n`
                );
                return yield* installed;
              }).pipe(Effect.orDie)
            )
          ),
        });
        yield* Effect.gen(function* () {
          const fs = yield* FileSystem.FileSystem;
          yield* (yield* named).sync({});
          const check = named.pipe(
            Effect.flatMap((workspace) => workspace.check()),
            Effect.provide(memoryWorkspaceServices())
          );
          const lock = yield* fs.readFile(`${root}/pnpm-lock.yaml`);
          expect(yield* check).toMatchObject({
            changes: [],
            dependencies: "current",
            ready: true,
          });
          const manifest = yield* fs.readFileString(
            "/source/apps/web/package.json"
          );
          yield* fs.writeFileString(
            "/source/apps/web/package.json",
            manifest.replace('"next": "catalog:"', '"next": "16.3.2"')
          );
          const changed = yield* check;
          expect(changed.dependencies).toBe("pending");
          expect(changed.dependencyReasons).toContain(
            "Installation inputs changed"
          );
          expect(changed.changes).toContainEqual({
            kind: "update",
            target: "apps/web/package.json",
          });
          expect(yield* fs.readFile(`${root}/pnpm-lock.yaml`)).toEqual(lock);
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect(
    "checks recorded installation without launching pnpm and keeps component freshness separate",
    () =>
      Effect.gen(function* () {
        const layer = yield* memoryWorkspace("application", { processes });
        yield* Effect.gen(function* () {
          const fs = yield* FileSystem.FileSystem;
          yield* (yield* named).sync({});
          const check = named.pipe(
            Effect.flatMap((workspace) => workspace.check()),
            Effect.provide(memoryWorkspaceServices())
          );
          expect(yield* check).toMatchObject({
            changes: [],
            dependencies: "current",
            ready: true,
          });
          const template = yield* fs.readFileString(
            "/source/layout.tsx.template"
          );
          yield* fs.writeFileString(
            "/source/layout.tsx.template",
            template.replace("Hello", "Welcome")
          );
          expect(yield* check).toMatchObject({
            changes: [{ kind: "update", target: "apps/web/layout.tsx" }],
            dependencies: "current",
            ready: false,
          });
          yield* fs.remove(`${root}/apps/web/node_modules/next/package.json`);
          const missing = yield* check;
          expect(missing.dependencies).toBe("pending");
          expect(missing.dependencyReasons).toContain(
            "Installed dependency missing: apps/web/node_modules/next/package.json"
          );
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect(
    "installs fresh applications without creating maintainer state",
    () =>
      Effect.gen(function* () {
        const layer = yield* memoryWorkspace("application", {
          processes: Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() => installedApplication("/application"))
          ),
        });
        yield* Effect.gen(function* () {
          const workspace = yield* (yield* Workspaces).fresh({
            destination: "/application",
            name: "garden",
            selection: { addOns: [], providers: {} },
            source: { kind: "working-tree", root: "/source" },
          });
          const result = yield* workspace.materialize({});
          const fs = yield* FileSystem.FileSystem;
          expect(result.dependencies).toBe("current");
          expect(
            yield* fs.exists("/application/node_modules/.modules.yaml")
          ).toBeTruthy();
          expect(
            yield* fs.exists("/application/.workspace-composition.json")
          ).toBeFalsy();
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect(
    "allows an explicit retry when the installer could not launch",
    () =>
      Effect.gen(function* () {
        const unavailable = Layer.effect(
          ChildProcessSpawner.ChildProcessSpawner,
          packageManager(() => installed).pipe(
            Effect.map((normal) =>
              ChildProcessSpawner.make((execution) =>
                execution._tag === "StandardCommand" &&
                execution.args.includes("install")
                  ? Effect.fail(
                      PlatformError.systemError({
                        _tag: "NotFound",
                        method: "spawn",
                        module: "ChildProcess",
                      })
                    )
                  : normal.spawn(execution)
              )
            )
          )
        );
        const layer = yield* memoryWorkspace("application", {
          processes: unavailable,
        });
        yield* Effect.gen(function* () {
          expect(
            yield* (yield* named).sync({}).pipe(Effect.flip)
          ).toMatchObject({
            _tag: "DependencyInstallationFailed",
            phase: "launch",
          });
          const retried = yield* named.pipe(
            Effect.flatMap((workspace) => workspace.sync({})),
            Effect.provide(memoryWorkspaceServices([], processes))
          );
          expect(retried.dependencies).toBe("current");
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect(
    "retries a stopped installation in another invocation without treating a skip as readiness",
    () =>
      Effect.gen(function* () {
        const entered = yield* Deferred.make<undefined>();
        const held = Deferred.succeed(entered, undefined).pipe(
          Effect.andThen(Effect.never)
        );
        const layer = yield* memoryWorkspace("application", {
          processes: Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() => held)
          ),
        });
        yield* Effect.gen(function* () {
          yield* named.pipe(
            Effect.flatMap((workspace) => workspace.sync({})),
            Effect.provide(memoryWorkspaceServices([], processes))
          );
          const workspace = yield* named;
          // Different installation options require a new attempt even though
          // the earlier successful installation still exists on disk.
          const running = yield* workspace
            .sync({ offline: true })
            .pipe(Effect.forkChild);
          yield* Deferred.await(entered);
          yield* Fiber.interrupt(running);
          expect(yield* workspace.check().pipe(Effect.flip)).toMatchObject({
            _tag: "WorkspaceRecoveryRequired",
          });
          const next = named.pipe(
            Effect.provide(memoryWorkspaceServices([], processes))
          );
          const skipped = yield* (yield* next).sync({ install: "skip" });
          expect(skipped.dependencies).toBe("pending");
          expect(yield* (yield* next).check()).toMatchObject({
            dependencies: "pending",
            ready: false,
          });
          expect(yield* (yield* next).sync({})).toMatchObject({
            dependencies: "current",
          });
          expect(yield* (yield* next).check()).toMatchObject({ ready: true });
        }).pipe(Effect.provide(layer));
      })
  );

  for (const target of ["pnpm-lock.yaml", "apps/web/layout.tsx"]) {
    it.effect(
      `preserves ${target} changed during an interrupted installation`,
      () =>
        Effect.gen(function* () {
          const entered = yield* Deferred.make<undefined>();
          const held = Deferred.succeed(entered, undefined).pipe(
            Effect.andThen(Effect.never)
          );
          const layer = yield* memoryWorkspace("application", {
            processes: Layer.effect(
              ChildProcessSpawner.ChildProcessSpawner,
              packageManager(() => held)
            ),
          });
          yield* Effect.gen(function* () {
            const fs = yield* FileSystem.FileSystem;
            const workspace = yield* named;
            const running = yield* workspace.sync({}).pipe(Effect.forkChild);
            yield* Deferred.await(entered);
            yield* fs.writeFileString(
              `${root}/${target}`,
              "unfinished changes\n"
            );
            yield* Fiber.interrupt(running);
            const retry = named.pipe(
              Effect.flatMap((next) => next.sync({})),
              Effect.provide(memoryWorkspaceServices([], processes))
            );
            expect(yield* retry.pipe(Effect.flip)).toMatchObject({
              _tag: "WorkspaceConflict",
              paths: [target],
            });
            expect(yield* fs.readFileString(`${root}/${target}`)).toBe(
              "unfinished changes\n"
            );
            expect(
              yield* fs.exists(`${root}/node_modules/.modules.yaml`)
            ).toBeFalsy();
          }).pipe(Effect.provide(layer));
        })
    );
  }

  it.effect(
    "does not publish readiness when recording a successful installation fails",
    () =>
      Effect.gen(function* () {
        const installationFinished = yield* Ref.make(false);
        const layer = yield* memoryWorkspace("application", {
          fileSystem: (fs) => ({
            ...fs,
            rename: (source, destination) =>
              Effect.gen(function* () {
                if (
                  destination === `${root}/.workspace-composition.json` &&
                  (yield* Ref.get(installationFinished))
                ) {
                  return yield* PlatformError.systemError({
                    _tag: "PermissionDenied",
                    method: "rename",
                    module: "FileSystem",
                    pathOrDescriptor: destination,
                  });
                }
                return yield* fs.rename(source, destination);
              }),
          }),
          processes: Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() =>
              installed.pipe(
                Effect.tap(() => Ref.set(installationFinished, true))
              )
            )
          ),
        });
        yield* Effect.gen(function* () {
          yield* (yield* named).sync({}).pipe(Effect.exit);
          const fs = yield* FileSystem.FileSystem;
          expect(
            yield* fs.exists(`${root}/node_modules/.modules.yaml`)
          ).toBeTruthy();
          expect(
            yield* fs.exists(`${root}/.workspace-composition.lock/receipt.json`)
          ).toBeTruthy();
          expect(
            yield* (yield* named).sync({}).pipe(Effect.flip)
          ).toMatchObject({ _tag: "WorkspaceLockAuthorizationRequired" });
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect(
    "reconciles executable install hooks instead of reusing manifest-only evidence",
    () =>
      Effect.gen(function* () {
        const layer = yield* memoryWorkspace("application", { processes });
        yield* Effect.gen(function* () {
          const fs = yield* FileSystem.FileSystem;
          const file = "/source/apps/web/package.json";
          const json = Schema.fromJsonString(
            Schema.Record(Schema.String, Schema.Unknown)
          );
          const manifest = yield* Schema.decodeEffect(json)(
            yield* fs.readFileString(file)
          );
          const scripts = yield* Schema.decodeUnknownEffect(
            Schema.Record(Schema.String, Schema.String)
          )(manifest.scripts);
          yield* fs.writeFileString(
            file,
            yield* Schema.encodeEffect(json)({
              ...manifest,
              scripts: { ...scripts, postinstall: "node setup.mjs" },
            })
          );
          yield* (yield* named).sync({});
          const failedInstaller = Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() => Effect.succeed(9))
          );
          const error = yield* named.pipe(
            Effect.flatMap((workspace) => workspace.sync({})),
            Effect.provide(memoryWorkspaceServices([], failedInstaller)),
            Effect.flip
          );
          expect(error).toMatchObject({
            _tag: "DependencyInstallationFailed",
            phase: "exit",
          });
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect(
    "installs after a files-only sync even when another invocation has no source changes",
    () =>
      Effect.gen(function* () {
        const layer = yield* memoryWorkspace("application", { processes });
        yield* Effect.gen(function* () {
          const first = yield* (yield* named).sync({ install: "skip" });
          expect(first.dependencies).toBe("pending");
          const second = yield* named.pipe(
            Effect.flatMap((workspace) => workspace.sync({})),
            Effect.provide(memoryWorkspaceServices([], processes))
          );
          expect(second.dependencies).toBe("current");
          expect(
            yield* (yield* FileSystem.FileSystem).exists(
              `${root}/node_modules/.pnpm/lock.yaml`
            )
          ).toBeTruthy();
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect(
    "reinstalls complete changed manifests after files-only synchronization",
    () =>
      Effect.gen(function* () {
        const layer = yield* memoryWorkspace("application", { processes });
        yield* Effect.gen(function* () {
          const fs = yield* FileSystem.FileSystem;
          yield* (yield* named).sync({});
          const file = "/source/apps/web/package.json";
          const json = Schema.fromJsonString(
            Schema.Record(Schema.String, Schema.Unknown)
          );
          const manifest = yield* Schema.decodeEffect(json)(
            yield* fs.readFileString(file)
          );
          yield* fs.writeFileString(
            file,
            yield* Schema.encodeEffect(json)({ ...manifest, version: "2.0.0" })
          );
          yield* (yield* named).sync({ install: "skip" });
          const failedInstaller = Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() => Effect.succeed(7))
          );
          const error = yield* named.pipe(
            Effect.flatMap((workspace) => workspace.sync({})),
            Effect.provide(memoryWorkspaceServices([], failedInstaller)),
            Effect.flip
          );
          expect(error).toMatchObject({
            _tag: "DependencyInstallationFailed",
            phase: "exit",
          });
          const retried = yield* named.pipe(
            Effect.flatMap((workspace) => workspace.sync({})),
            Effect.provide(memoryWorkspaceServices([], processes))
          );
          expect(retried.dependencies).toBe("current");
          expect(
            yield* fs.readFileString(`${root}/apps/web/package.json`)
          ).toContain('"2.0.0"');
          expect(yield* fs.exists(`${root}/apps/web/layout.tsx`)).toBeTruthy();
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect(
    "does not certify a manifest edited while installation holds the workspace lease",
    () =>
      Effect.gen(function* () {
        const entered = yield* Deferred.make<undefined>();
        const release = yield* Deferred.make<undefined>();
        const held = Deferred.succeed(entered, undefined).pipe(
          Effect.andThen(Deferred.await(release)),
          Effect.andThen(installed)
        );
        const layer = yield* memoryWorkspace("application", {
          processes: Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() => held)
          ),
        });
        yield* Effect.gen(function* () {
          const workspace = yield* named;
          const running = yield* workspace.sync({}).pipe(Effect.forkChild);
          yield* Deferred.await(entered);
          expect(yield* workspace.sync({}).pipe(Effect.flip)).toMatchObject({
            _tag: "WorkspaceLockAuthorizationRequired",
          });
          const fs = yield* FileSystem.FileSystem;
          yield* fs.writeFileString(
            `${root}/apps/web/package.json`,
            '{"name":"edited-during-install"}'
          );
          yield* Deferred.succeed(release, undefined);
          expect(yield* Fiber.join(running).pipe(Effect.flip)).toMatchObject({
            _tag: "DependencyInstallationFailed",
            phase: "inputs",
          });
          expect(yield* workspace.sync({}).pipe(Effect.flip)).toMatchObject({
            _tag: "WorkspaceConflict",
            paths: ["apps/web/package.json"],
          });
          expect(
            yield* fs.readFileString(`${root}/apps/web/package.json`)
          ).toBe('{"name":"edited-during-install"}');
        }).pipe(Effect.provide(layer));
      })
  );

  it.effect("reinstalls when installed output evidence was removed", () =>
    Effect.gen(function* () {
      const layer = yield* memoryWorkspace("application", { processes });
      yield* Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        yield* (yield* named).sync({});
        yield* fs.remove(`${root}/node_modules/.modules.yaml`);
        const result = yield* (yield* named).sync({});
        expect(result.dependencies).toBe("current");
        expect(
          yield* fs.readFileString(`${root}/node_modules/.modules.yaml`)
        ).toBe("layoutVersion: 5\n");
      }).pipe(Effect.provide(layer));
    })
  );

  it.effect(
    "preserves pnpm normalization and reuses installation after a component-only edit",
    () =>
      Effect.gen(function* () {
        const normalize = Effect.gen(function* () {
          const fs = yield* FileSystem.FileSystem;
          yield* fs.writeFileString(
            `${root}/pnpm-lock.yaml`,
            `${yield* fs.readFileString(`${root}/pnpm-lock.yaml`)}\n# normalized by installer\n`
          );
          return yield* installed;
        }).pipe(Effect.orDie);
        const layer = yield* memoryWorkspace("application", {
          processes: Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() => normalize)
          ),
        });
        yield* Effect.gen(function* () {
          const fs = yield* FileSystem.FileSystem;
          yield* (yield* named).sync({});
          const lockfile = yield* fs.readFileString(`${root}/pnpm-lock.yaml`);
          yield* fs.writeFileString(
            "/source/layout.tsx.template",
            (yield* fs.readFileString("/source/layout.tsx.template")).replace(
              "Hello",
              "Welcome"
            )
          );
          const noInstall = Layer.effect(
            ChildProcessSpawner.ChildProcessSpawner,
            packageManager(() =>
              Effect.die(new Error("Component edit must not reinstall"))
            )
          );
          const result = yield* named.pipe(
            Effect.flatMap((workspace) => workspace.sync({})),
            Effect.provide(memoryWorkspaceServices([], noInstall))
          );
          expect(result.dependencies).toBe("current");
          expect(yield* fs.readFileString(`${root}/pnpm-lock.yaml`)).toBe(
            lockfile
          );
          expect(
            yield* fs.readFileString(`${root}/apps/web/layout.tsx`)
          ).toContain("Welcome");
        }).pipe(Effect.provide(layer));
      })
  );
});
