import type { PlannedRoute } from "./types.js";

const GENERATED_HEADER =
  "// Generated by create-next-hydra. Changes will be replaced by `create-next-hydra use`.";

export type GeneratedRoute = {
  target: string;
  content: string;
};

function exportSpecifier(route: PlannedRoute): string {
  return route.export === route.method
    ? route.method
    : `${route.export} as ${route.method}`;
}

function exportBlock(module: string, routes: PlannedRoute[]): string {
  if (routes.length === 1 && routes[0]) {
    return `export { ${exportSpecifier(routes[0])} } from ${JSON.stringify(module)};`;
  }

  return `export {\n${routes
    .sort((left, right) => left.method.localeCompare(right.method))
    .map((route) => `  ${exportSpecifier(route)},`)
    .join("\n")}\n} from ${JSON.stringify(module)};`;
}

export function generateRoutes(routes: PlannedRoute[]): GeneratedRoute[] {
  const byTarget = new Map<string, PlannedRoute[]>();

  for (const route of routes) {
    const existing = byTarget.get(route.target) ?? [];
    existing.push(route);
    byTarget.set(route.target, existing);
  }

  return [...byTarget.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([target, targetRoutes]) => {
      const byModule = new Map<string, PlannedRoute[]>();
      for (const route of targetRoutes) {
        const moduleRoutes = byModule.get(route.module) ?? [];
        moduleRoutes.push(route);
        byModule.set(route.module, moduleRoutes);
      }
      const exports = [...byModule.entries()]
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([module, moduleRoutes]) => exportBlock(module, moduleRoutes))
        .join("\n");
      return { content: `${GENERATED_HEADER}\n${exports}\n`, target };
    });
}
