#!/bin/bash

# Description: Installs the Next Hydra Drupal starter.

set -euo pipefail

## Start DDEV
ddev start

## Install Dependencies
ddev composer install

## Install Drupal
ddev drush site:install minimal --verbose -y

## Apply the Hydra content model and demo content
ddev drush recipe ../recipes/next-hydra-starter -v
ddev drush cr

### Generate scopes
ddev drush php:script scripts/scopes

### Generate consumers
ddev drush php:script scripts/consumers

### Rebuild permissions
ddev drush php-eval 'node_access_rebuild();'

ddev drush cr

ddev drush uli
