export const workspaceEnvironment = (nodeEnv: "test" | "production") => ({
  // Preserve process essentials, not live provider credentials or test-runner NODE_ENV.
  ...Object.fromEntries(
    Object.entries(process.env).filter(([name]) =>
      [
        "PATH",
        "HOME",
        "USERPROFILE",
        "SystemRoot",
        "TMPDIR",
        "TMP",
        "TEMP",
        "LANG",
        "NODE_EXTRA_CA_CERTS",
        "SSL_CERT_FILE",
      ].includes(name)
    )
  ),
  ADMIN_CLERK_AUTHORIZED_PARTIES: "https://admin.customer-project.localhost",
  ADMIN_CLERK_PUBLISHABLE_KEY: "pk_test_admin_publishable",
  ADMIN_CLERK_SECRET_KEY: "sk_test_admin_secret",
  ADMIN_URL: "https://admin.customer-project.localhost",
  ADMIN_WORKOS_API_KEY: "sk_test_admin",
  ADMIN_WORKOS_CLIENT_ID: "client_test_admin",
  CI: "1",
  CLERK_AUTHORIZED_PARTIES: "https://web.customer-project.localhost",
  CLERK_SECRET_KEY: "sk_test_secret",
  CLERK_WEBHOOK_SECRET: "whsec_test",
  COMMERCETOOLS_CLIENT_ID: "test-client",
  COMMERCETOOLS_CLIENT_SECRET: "test-secret",
  COMMERCETOOLS_PROJECT_KEY: "test-project",
  COMMERCETOOLS_REGION: "test-region",
  COMMERCETOOLS_SCOPE: "manage_project:test-project",
  CONTENTSTACK_API_KEY: "test-api-key",
  CONTENTSTACK_DELIVERY_TOKEN: "cs-test-delivery",
  CONTENTSTACK_ENVIRONMENT: "test",
  CONTENTSTACK_PREVIEW_TOKEN: "cs-test-preview",
  CONTENTSTACK_WEBHOOK_SECRET: "test-webhook-secret",
  DRUPAL_BASE_URL: "https://drupal.example.com",
  DRUPAL_PREVIEWER_CLIENT_ID: "test-preview-client",
  DRUPAL_PREVIEWER_CLIENT_SECRET: "test-preview-secret",
  DRUPAL_VIEWER_CLIENT_ID: "test-viewer-client",
  DRUPAL_VIEWER_CLIENT_SECRET: "test-viewer-secret",
  NEXT_PUBLIC_API_URL: "https://api.customer-project.localhost",
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_publishable",
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: "/",
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in",
  NEXT_PUBLIC_CONTENTSTACK_API_KEY: "test-api-key",
  NEXT_PUBLIC_CONTENTSTACK_ENVIRONMENT: "test",
  NEXT_PUBLIC_POSTHOG_HOST: "https://posthog.example.com",
  NEXT_PUBLIC_POSTHOG_KEY: "phc_test",
  NEXT_PUBLIC_WEB_URL: "https://web.customer-project.localhost",
  NEXT_PUBLIC_WORKOS_REDIRECT_URI:
    "https://web.customer-project.localhost/api/auth/callback",
  NEXT_TELEMETRY_DISABLED: "1",
  NODE_ENV: nodeEnv,
  REGISTRATION_APPROVER_EMAIL: "approver@example.com",
  RESEND_FROM: "test@example.com",
  RESEND_TOKEN: "re_test",
  STRIPE_PUBLISHABLE_KEY: "pk_test_fixture",
  STRIPE_SECRET_KEY: "sk_test_fixture",
  TURBO_TELEMETRY_DISABLED: "1",
  WORKOS_API_KEY: "sk_test",
  WORKOS_CLIENT_ID: "client_test",
  WORKOS_COOKIE_PASSWORD: "test-cookie-password-at-least-32-characters",
  WORKOS_WEBHOOK_SECRET: "whsec_test",
});
